project: 
  type: website

website:
  title: "2022 LP DAAC UWG Breakout Session"
  site-url: https://nasa-openscapes.github.io/2022-LPDAAC-UWG-Breakout/
  repo-url: https://github.com/NASA-Openscapes/2022-LPDAAC-UWG-Breakout
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "LPDAAC (2022). 2022 LP DAAC UWG Breakout Session"
 
  navbar: 
    background: primary
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/NASA-Openscapes/2022-LPDAAC-UWG-Breakout
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: img/lpdaac-logo-black.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - index.md           

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
